# Generated by Django 2.1.5 on 2019-01-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mob', models.TextField(max_length=13)),
                ('isveg', models.BooleanField(default=True)),
                ('accomadation', models.BooleanField(default=True)),
                ('is_ieee_member', models.BooleanField(default=True)),
                ('member_id', models.TextField(blank=True, max_length=100, null=True)),
                ('college', models.TextField(max_length=100)),
                ('t_shirt_size', models.TextField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=1)),
            ],
        ),
    ]
