# Generated by Django 2.1.5 on 2019-01-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190116_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='accomadation',
            new_name='accommodation',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='isveg',
            new_name='is_veg',
        ),
    ]
