# Generated by Django 2.1.5 on 2019-01-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190116_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='referral_code',
            field=models.CharField(default='ksasa', max_length=10),
            preserve_default=False,
        ),
    ]
