# Generated by Django 2.1.5 on 2019-01-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_registration_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
